---

# This is the meta auter-manager playbook.
# This playbook gathers plays auter_install and auter_schedule to:
#   - install / configure auter, configsnap and nimbus
#   - set up auter prep and apply schedules
#
# All configuration should be present in a csv file matching
# auter_config_template.csv format/definition.

- hosts: all
  become: True
  gather_facts: False
  vars_prompt:
    - name: "ini_csv_file"
      prompt: "Enter config file (defaults to ./auter_config.csv)"
      default: "./auter_config.csv"
      private: no

  roles:
    - { role: auter_installer, tags: [ install ] }
    - { role: auter_scheduler, tags: [ schedule ] }

...
