---

- name: Pre-check if server has configuration set in CSV file
  tags:
    - prechecks
    - install
  become: False
  changed_when: False
  local_action: command grep ^{{ inventory_hostname.split(':')[0] }}, {{ csv_file }}

- name: Check if epel repo is present
  tags: prechecks,auter,configsnap
  shell: time yum repolist | grep epel | wc -l
  register: epelPresent
  changed_when: False
  # basically always return OK during execution

- name: add the rs-epel repo
  tags:
    - auter
    - configsnap
    - install
  failed_when: False
  register: result
  yum:
    name: rs-epel-release
    state: latest
  when: epelPresent.stdout|int == 0

- name: add the epel repo
  tags:
    - auter
    - configsnap
    - install
  yum:
    name: epel-release
    state: latest
  when: >
    epelPresent.stdout|int == 0 and
    "no package" in result.msg|lower

- import_tasks: auter.yml
  tags:
    - auter
    - install
- import_tasks: configsnap.yml
  tags:
    - install
    - configure
    - configsnap
- import_tasks: nimbus.yml
  tags:
    - install
    - configure
    - nimbus

...
