---

- import_tasks: prepare.yml
  tags:
    - prechecks
    - prepare

- import_tasks: auter.yml
  tags:
    - auter
    - install
- import_tasks: configsnap.yml
  tags:
    - install
    - configure
    - configsnap
- import_tasks: nimbus.yml
  tags:
    - install
    - configure
    - nimbus

...
