---
- hosts: all
  become: True
  gather_facts: False
  vars: 
    csv_file: ./auter_config.csv
  tasks:
    - name: Pre-check if server has configuration set in CSV file
      become: False
      changed_when: False
      local_action: command grep ^{{ inventory_hostname }}, {{ csv_file }}

    - name: add the rs-epel repo
      failed_when: False
      register: result
      yum:
        name: rs-epel-release
        state: latest
      
    - name: add the epel repo
      when: "'No Package' in result.msg"
      yum:
        name: epel-release
        state: latest
      
    - name: install auter
      yum:
        name: auter
        state: latest

    - name: adjust the auter.conf file
      template:
        src: auter.conf.j2
        dest: /etc/auter/auter.conf

    - name: add warning to not edit yum.conf exclude manually
      lineinfile:
        line: "# WARNING: the excludes line is edited by auter_installer everytime it is run"
        insertbefore: "^exclude="
        dest: /etc/yum.conf

    - name: adjust the yum.conf excludes
      lineinfile:
        dest: /etc/yum.conf
        state: present
        regexp: ^exclude
        line: exclude={{ lookup('csvfile', inventory_hostname + ' file=' + csv_file + ' col=1 delimiter=,') }}

    - name: download configsnap to local directory
      become: False
      local_action: get_url
                    dest="./configsnap"
                    url="https://raw.githubusercontent.com/rackerlabs/configsnap/master/configsnap"

    - name: copy configsnap script to server
      copy:
        backup: yes
        dest: /usr/bin/configsnap
        group: root
        owner: root
        mode: 0755
        src: ./configsnap

    - name: create configsnap pre apply script
      lineinfile: 
        create: yes
        state: present
        dest: /etc/auter/pre-apply.d/01-configsnap-pre
        mode: 0755
        line: /usr/bin/configsnap --silent -d /root -t auter-configsnap-$(date +%Y-%m-%d) -p pre
 
    - name: create configsnap post apply script
      lineinfile: 
        create: yes
        state: present
        dest: /etc/auter/post-apply.d/50-configsnap-post-apply
        mode: 0755
        line: /usr/bin/configsnap -d /root -t auter-configsnap-$(date +%Y-%m-%d) -p post-update &> /root/auter-configsnap-$(date +%Y-%m-%d)/configsnap/post-update.compare

    - name: create configsnap post reboot script
      lineinfile: 
        create: yes
        state: present
        dest: /etc/auter/post-reboot.d/99-configsnap-post-reboot
        mode: 0755
        line: /usr/bin/configsnap -d /root -t auter-configsnap-$(date +%Y-%m-%d) -p post-reboot &> /root/auter-configsnap-$(date +%Y-%m-%d)/configsnap/post-reboot.compare

    - name: enable auter
      command: auter --enable

    - name: remove downloaded configsnap from local directory
      become: False
      ignore_errors: True
      local_action: file
                    dest="./configsnap"
                    state=absent
...
