---
- hosts: all
  vars:
    csv_file: ./auter-audit-{{ ansible_date_time.date }}.csv
    
  tasks:
    - script: ./auter-audit.sh -c
      become: True
      register: auter_audit_output
     
#    - debug: msg={{ auter_audit_output.stdout_lines[3] }}

    - local_action: stat path={{ csv_file }}
      become: False
      register: csv

    - name: Write header
      local_action: lineinfile
                    create=yes
                    state=present
                    dest={{ csv_file }}
                    line='Hostname,Version,Status,LastUpdate'
      when: csv.stat.exists == False

    - name: Append output to CSV file
      local_action: lineinfile
                    create=yes
                    state=present
                    dest={{ csv_file }}
                    line={{ auter_audit_output.stdout_lines[3] }}
...

