---
- hosts: all
  gather_facts: False
  vars:
    csv_file: ./auter-audit.csv
    username: "none"
    appstatssource: "auter-manager"
    appstatsappid: "auter-manager"
    appstatsfunctionid: "reporter"

    
  tasks:
    - local_action: 'shell date +%D'
      become: False
      register: currentdate

    - debug: 
        var: currentdate


    - script: ./auter-audit.sh -c
      become: True
      register: auter_audit_output
     
#    - debug: msg={{ auter_audit_output.stdout_lines[4] }}

    - local_action: stat path={{ csv_file }}-{{ currentdate }}
      become: False
      register: csv

    - name: Write header
      local_action: lineinfile
                    create=yes
                    state=present
                    dest={{ csv_file }}-{{ currentdate }}
                    line='Hostname,Version,Status,LastUpdate'
      when: csv.stat.exists == False

    - name: Append output to CSV file
      local_action: lineinfile
                    create=yes
                    state=present
                    dest={{ csv_file }}-{{ currentdate }}
                    line={{ auter_audit_output.stdout_lines[4] }}

    - name: Get SSO from ~/.config/hammertime/config.yaml
      become: false
      local_action:
        module: shell awk '/^\s+username:.*[a-z]/ {print $2;exit;}' $HOME/.config/hammertime/config.yaml
      register: username
      failed_when: False

    - name: Appstats report
      local_action:
        module: uri
        url: 'https://appstats.rackspace.com/appstats/event/'
        method: 'POST'
        HEADER_Content-Type: application/json
        body: '{
          "username": "{{ username.stdout }}",
          "status": "SUCCESS",
          "source": "{{ appstatssource }}",
          "appid": "{{ appstatsappid }}",
          "OS": "Linux",
          "functionid": "{{ appstatsfunctionid }}"
        }'
        body_format: json
      become: False
      failed_when: False
...

