---
- hosts: all
  tasks:
    - name: get auter status
      become: true
      shell: auter --status
      register: auter_status

    - name: add the rs-epel repo
      become: true
      failed_when: False
      register: result
      yum:
        name: rs-epel-release
        state: latest
      
    - name: install auter
      become: true
      yum:
        name: auter
        state: latest

#    - name: adjust the auter.conf file
#      template:
#        src: auter.conf.j2
#        dest: /etc/auter/auter.conf

#    - name: adjust the yum.conf excludes
#      lineinfile:
#        dest: /etc/yum.conf
#        state: present
#        regexp: ^exclude
#        line: exclude={{ lookup('csvfile', inventory_hostname + ' file=auter-config.csv col=1 delimiter=,') }}

    - local_action: get_url
                    dest="./getData"
                    url="https://raw.githubusercontent.com/rackerlabs/getData/master/getData"

    - name: copy get-Data script to server
      become: true
      copy:
        backup: yes
        dest: /usr/bin/getData
        force: yes
        group: root
        owner: root
        mode: 0755
        src: ./getData

    - name: Check if there are any pre-apply scripts
      become: true
      shell: find /var/lib/auter/pre-apply.d -type f 2>/dev/null| wc -l
      ignore_errors: True
      register: pre_apply 

    - name: copy all scripts to /etc/auter/pre-apply.d/
      become: true
      shell: mv /var/lib/auter/pre-apply.d/* /etc/auter/pre-apply.d/
      when: pre_apply.stdout|int != 0
      
    - name: Check if there are any post-apply scripts
      become: true
      shell: find /var/lib/auter/post-apply.d -type f | wc -l
      ignore_errors: True
      register: post_apply 

    - name: copy all scripts to /etc/auter/post-apply.d/
      become: true
      shell: mv /var/lib/auter/post-apply.d/* /etc/auter/post-apply.d/
      when: post_apply.stdout|int > 0
     
    - name: Check if there are any pre-reboot scripts
      become: true
      shell: find /var/lib/auter/pre-reboot.d -type f | wc -l
      ignore_errors: True
      register: pre_reboot 

    - name: copy all scripts to /etc/auter/pre-reboot.d/
      become: true
      shell: mv /var/lib/auter/pre-reboot.d/* /etc/auter/pre-reboot.d/
      when: pre_reboot.stdout|int > 0
      
    - name: Check if there are any post-reboot scripts
      become: true
      shell: find /var/lib/auter/post-reboot.d -type f | wc -l
      ignore_errors: True
      register: post_reboot 

    - name: copy all scripts to /etc/auter/post-reboot.d/
      become: true
      shell: mv /var/lib/auter/post-reboot.d/* /etc/auter/post-reboot.d/
      when: post_reboot.stdout|int > 0
      
    - name: Check if any of the scripts contain getData
      become: true
      shell: grep -ri getData /etc/auter/* | wc -l
      register: getdata_detected

    - name: create get-Data pre apply script
      become: true
      lineinfile: 
        create: yes
        state: present
        dest: /etc/auter/pre-apply.d/01-auter-pre
        mode: 0755
        line: /usr/bin/getData --silent -d /root -t auter-getData-$(date +%Y-%m-%d) -p pre
      when: getdata_detected.stdout|int == 0
 
    - name: create get-Data post apply script
      become: true
      lineinfile: 
        create: yes
        state: present
        dest: /etc/auter/post-apply.d/01-auter-post-apply
        mode: 0755
        line: /usr/bin/getData -d /root -t auter-getData-$(date +%Y-%m-%d) -p post-update &> /root/auter-getData-$(date +%Y-%m-%d)/getData/post-update.compare
      when: getdata_detected.stdout|int == 0

    - name: create get-Data post reboot script
      become: true
      lineinfile: 
        create: yes
        state: present
        dest: /etc/auter/post-reboot.d/99-auter-post-reboot
        mode: 0755
        line: /usr/bin/getData -d /root -t auter-getData-$(date +%Y-%m-%d) -p post-reboot &> /root/auter-getData-$(date +%Y-%m-%d)/getData/post-reboot.compare
      when: getdata_detected.stdout|int == 0

    - name: enable auter
      become: true
      command: auter --enable
      when: "'enabled' in auter_status.stdout"

    - local_action: file
                    dest="./getData"
                    state=absent
